### ISSUE TITLE
QU240wISC test broken

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#658]
The QU240wISC test case no longer works on the latest `ocean/develop` (1550912b1).

On Grizzly, I built using the following setup:
```
echo "Loading modules for grizzly with intel and scorpio"
module purge
module use /usr/projects/climate/SHARED_CLIMATE/modulefiles/all/
module load git
if [ -f "load_compass_env.sh" ]; then
    source load_compass_env.sh
else
    source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/etc/profile.d/conda.sh
    conda activate compass_0.1.8
fi

module load friendly-testing
module load intel/19.0.4 intel-mpi/2019.4 hdf5-parallel/1.8.16 pnetcdf/1.11.2 netcdf-h5parallel/4.7.3 mkl/2019.0.4 scorpio/pio2/1.10.1
export I_MPI_CC=icc
export I_MPI_CXX=icpc
export I_MPI_F77=ifort
export I_MPI_F90=ifort
export CORE=ocean
export USE_PIO2=true
export AUTOCLEAN=true

export  HDF5_USE_FILE_LOCKING=FALSE
```

I did a `make clean` and `make ifort` (as usual).

When I run the `initial_state` step of the test case, I see:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
ocean_model        0000000000C3D2C3  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00002AC8E88DC630  Unknown               Unknown  Unknown
ocean_model        000000000098B709  Unknown               Unknown  Unknown
ocean_model        000000000075B8E8  Unknown               Unknown  Unknown
ocean_model        00000000007662C6  Unknown               Unknown  Unknown
ocean_model        000000000060051F  Unknown               Unknown  Unknown
ocean_model        00000000006F7BD2  Unknown               Unknown  Unknown
ocean_model        0000000000412CA7  Unknown               Unknown  Unknown
ocean_model        0000000000412C2E  Unknown               Unknown  Unknown
ocean_model        0000000000412BD2  Unknown               Unknown  Unknown
libc-2.17.so       00002AC8E9011555  __libc_start_main     Unknown  Unknown
ocean_model        0000000000412AE9  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 11120 RUNNING AT gr0014
=   EXIT STATUS: 174
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 11121 RUNNING AT gr0014
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 11122 RUNNING AT gr0014
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 11123 RUNNING AT gr0014
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
Traceback (most recent call last):
  File "./run.py", line 30, in <module>
    subprocess.check_call(['mpirun', '-n', '4', './ocean_model', '-n',
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-n', '4', './ocean_model', '-n', 'namelist.ocean', '-s', 'streams.ocean']' returned non-zero exit status 255.
```

**Comment by mark-petersen** [comment]
This is now fixed by #659
